### ISSUE TITLE
Cokurtosis Matrix

### ISSUE THREAD

**Issue by wapebira** [johnsoong216/pymarkowitz#4]
It looks like when we compare the kurtosis values calculated with pandas builtin function versus the generator through the diagonal they do not match. Even in the demo notebook they do not match.
![image](https://user-images.githubusercontent.com/33706212/103447694-a4c4df80-4c5c-11eb-9ef4-2065873dadaf.png)

I was not able to test using your sample because of memory allocation issue on my machine, but do not match using other smaller dataset.

**Comment by johnsoong216** [comment]
I just updated the kurtosis calculations. Notice that the pandas built-in kurtosis uses unbiased estimator but the method I used is biased so you could compare it by importing kurtosis method from scipy and they should be consistent now
